# -*- coding: utf-8 -*-
"""internet_tester

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMpef0KCs9gbD16RBm56lp798wpbmzRo
"""

pip install speedtest-cli

import speedtest
test = speedtest.Speedtest()
down = test.download()
upload = test.upload()
print(f"Download speed: {down}")
print(f"Upload speed: {upload}")